- name: AAP Test Sample
  hosts: all
  tasks:
    - name: hostname Command
      ansible.builtin.command: hostname
      register: hostname_result

    - name: Show hostname_result
      ansible.builtin.debug: 
        msg: hostname_result.stdout
